//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace softcomputacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reparacion
    {
        public int idReparacion { get; set; }
        public System.DateTime fecha { get; set; }
        public int idEstado { get; set; }
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public string observaciones { get; set; }
        public string producto { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estado estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
