//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace softcomputacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.detallePago = new HashSet<detallePago>();
            this.detalleVenta = new HashSet<detalleVenta>();
        }
    
        public int idVenta { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public int idUsuario { get; set; }
        public decimal costoTotal { get; set; }
        public Nullable<int> cantidadProductosTotal { get; set; }
        public Nullable<int> idCliente { get; set; }
        public int idEstado { get; set; }
        public Nullable<decimal> entregado { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallePago> detallePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleVenta> detalleVenta { get; set; }
        public virtual estado estado { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
